[build]
command = "gulp"
publish = "public"

[dev]
command = "gulp watch"
port = 3000

# Redirect from Netlify to my domain
[[redirects]]
  from = "http://arrakis.netlify.com/*"
  to = "https://arrak.is/:splat"
  status = 301
  force = true
