[build]
command = "sudo apt-get install pandoc && gulp"
publish = "dist"

# Redirect from Netlify to my domain
[[redirects]]
from = "http://arrakis.netlify.com/*"
to = "https://arrak.is/:splat"
status = 301
force = true
